# Generated by Django 5.0 on 2024-01-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='+48000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='postal_code',
            field=models.CharField(default='00-950', max_length=6),
        ),
        migrations.AddField(
            model_name='customuser',
            name='town_name',
            field=models.CharField(default='Warsaw', max_length=32),
        ),
    ]
